Repository OpenRadioss/OpenRadioss, pull requests merged in 2023-01, with the labels that each got.

#1007 Possible segfault in /INTER/TYPE25
  engine/source/mpi/interfaces/spmd_tri25vox.F
Labels: bug, engine

#1011 correction bug Skidline output
  engine/source/interfaces/int21/i21ass3.F
Labels: bug, engine

#1010 LAW88 , wrong behavior in Shear
  engine/source/materials/mat/mat088/sigeps88c.F
Labels: bug, engine

#1013 various bugs found with address sanitizers
  starter/source/constraints/general/mpc/hm_read_mpc.F
  starter/source/constraints/general/rbe3/hm_read_rbe3.F
  starter/source/constraints/general/rwall/hm_read_rwall_lagmul.F
  starter/source/constraints/general/rwall/hm_read_rwall_therm.F
  starter/source/elements/initia/scaleini.F
  starter/source/elements/solid/solide/sgrtails.F
Labels: bug, starter

#1036 EOS%VAR:initialization fix
  engine/source/multifluid/multi_inlet_ebcs.F
  starter/source/elements/elbuf_init/ini_eos_vars.F
  starter/source/initial_conditions/inigrav/inigrav_eos.F
  starter/source/restart/ddsplit/w_elbuf_str.F
Labels: bug

#1032 Fix timestep computation in starter for /MAT/LAW53
  starter/source/materials/mat/mat053/hm_read_mat53.F
Labels: bug

#1033 /SENSOR/VEL : convert global node number to local for spmd
  starter/source/tools/sensor/write_sensor_tab.F
Labels: bug

#996 allows part selection for /H3D/NODA/GPS/TMAX to save computation times
  common_source/modules/outmax_mod.F
  engine/source/engine/resol.F
  engine/source/engine/resol_init.F
  engine/source/mpi/generic/spmd_exch_v.F
  engine/source/output/anim/generate/tensgpstrain.F
  engine/source/output/anim/generate/tensor6.F
  engine/source/output/h3d/h3d_results/h3d_nodal_tensor.F
  engine/source/output/outmaxsubr.F
  engine/source/output/tmax_ipart.F
  engine/source/output/upd_outmax.F
  engine/source/system/timer.F
Labels: enhancement, engine

#1035 /SENSOR/ENERGY : correct bug with constant energy criterion
  engine/source/tools/sensor/sensor_energy.F
Labels: bug

#1037 H3D/ANIM:New output, Tillotson EoS region identifier in p,v diagram
  common_source/eos/eosmain.F
  common_source/eos/tillotson.F
  engine/source/output/anim/generate/dfunc6.F
  engine/source/output/anim/generate/dfuncc.F
  engine/source/output/anim/generate/genani.F
  engine/source/output/anim/reader/anim_dcod_key_0.F
  engine/source/output/h3d/h3d_results/h3d_quad_scalar.F
  engine/source/output/h3d/h3d_results/h3d_solid_scalar_1.F
  engine/source/output/h3d/h3d_results/h3d_sph_scalar.F
  engine/source/output/h3d/input_list/h3d_list_quad_scalar.F
  engine/source/output/h3d/input_list/h3d_list_solid_scalar.F
  engine/source/output/h3d/input_list/h3d_list_sph_scalar.F
  starter/source/materials/eos/hm_read_eos.F
  starter/source/materials/eos/hm_read_eos_tillotson.F
Labels: enhancement

#1042 /INTER/TYPE18:improving output in Starter listing file
  starter/source/interfaces/int18/hm_read_inter_type18.F
Labels: enhancement
