Repository OpenRadioss/OpenRadioss, pull requests merged in 2023-06, with the labels that each got.

#1522 bug fixing in /H3D/ELEM/PEXT for /LOAD_PRESSURE
  engine/source/output/h3d/h3d_results/h3d_skin_ixskin.F
Labels: important

#1531 wrong mapping result with /INIBRI/EREF+LAW95 for tet elements
  starter/source/elements/solid/solide10/s10jaci3.F
  starter/source/elements/solid/solide4/s4init3.F
  starter/source/elements/solid/solide4/s4jaci3.F
Labels: important

#1543 correct applied pressure distribution on segment nodes in /LOAD/PCYL
  engine/source/loads/general/load_pcyl/press_seg3.F
  engine/source/loads/general/load_pcyl/pressure_cyl.F
Labels: important

#1569 Correction of GAUGE option in time history
  engine/source/ale/agauge.F
  engine/source/ale/alemain.F
  engine/source/ale/alethe.F
Labels: important

#1583 Correction problem th/surf P ouptut pblast load
  engine/source/engine/resol.F
  starter/source/restart/ddsplit/w_th_surf_loadp.F
Labels: important

#1563 adding product_name & correct the listing file and improve the error 373 message
  hm_cfg_files/config/CFG/radioss2023/PLY/ply.cfg
  hm_cfg_files/config/CFG/radioss2023/PLY/prop_ply.cfg
  starter/source/elements/shell/coque/lcgeo19.F
  starter/source/output/message/starter_message_description.txt
Labels: important

#1588 Fix FVMBAG warning message doubled IDs 2069
  starter/source/airbag/monvol_check_delete_duplicated.F
  starter/source/output/message/starter_message_description.txt
Labels: important

#1592 remove repetitive Ishel error message in Starter
  starter/source/elements/sh3n/coque3n/c3grtails.F
  starter/source/elements/shell/coque/cgrtails.F
  starter/source/output/message/starter_message_description.txt
Labels: important

#1605 bug of tetra4 element +Ismstr>=10 when the connectivity has been changed due to negative Jacobian
  starter/source/elements/solid/solide/scoor3.F
Labels: important

#1609 Fix an issue in plist_ifront
  starter/source/spmd/node/ddtools.F
Labels: important

#1618 fix an uninitialized variable introduced by 226e90fd29dbaefd7924118f2193818fb487a104
  engine/source/output/anim/reader/anim_build_index_all.F
Labels: bug, engine, important

#1622 Inter7 thermal exchange debug
  engine/source/interfaces/int07/i7therm.F
  engine/source/interfaces/int21/i21therm.F
Labels: important

#1617 SEATBELT - no more error message in case of bifurcation
  starter/source/output/message/starter_message_description.txt
  starter/source/tools/seatbelts/new_seatbelt.F
Labels: important

#1620 Correction H3d output CONT/MAX PCONT/MAX stamping memory problem
  engine/source/output/h3d/h3d_results/h3d_nodal_vector.F
Labels: important

#1614 change early connectivity order for negative Jacobian avoid negative stiffness of contact
  starter/source/elements/reader/hm_read_solid.F
  starter/source/starter/lectur.F
Labels: bug, important

#1648 i7remnode issue : the size of the array INSERTED_NODE is not correct
  starter/source/interfaces/inter3d1/i7remnode.F
Labels: bug, starter, important
