Repository OpenRadioss/OpenRadioss, pull requests merged in 2024-11, with the labels that each got.

#3119 Fix message 3066
  starter/source/elements/joint/rjoint/rini45.F
  starter/source/output/message/starter_message_description.txt
Labels: important

#3117 Correction of user material laws for orthotropic solids
  engine/source/materials/mat_share/mulaw.F90
  engine/source/materials/mat_share/usermat_solid.F
  starter/source/materials/mat/mat028/hm_read_mat28.F
Labels: important

#3126 CHKPT fix
  engine/source/output/restart/rdcomm.F
  engine/source/output/restart/wrcomm.F
  starter/source/restart/ddsplit/wrcomm.F
Labels: important

#3130 Fix some uninitizalized variables
  common_source/modules/loads/pblast_mod.F
  common_source/modules/python_element_mod.F90
  common_source/tools/clipping/polygon_clipping_mod.F90
  engine/source/materials/mat_share/usermat_solid.F
  engine/source/tools/curve/finter.F
  engine/source/tools/curve/finter_smooth.F
  starter/CMake_Compilers/cmake_linux64_gf.txt
  starter/source/tools/curve/finter.F
Labels: important

#3140 fixing R2R deallocating issue
  starter/source/starter/lectur.F
Labels: bug

#3146 correct non initialized variable in starter for /fail/alter and /fail/fractal_dmg
  starter/source/materials/fail/fractal/fractal_element_neighbor.F90
  starter/source/materials/fail/windshield_alter/brokmann_random.F90
Labels: bug, starter, important

#3152 correct non initialized local variables used in thermal options for shells
  engine/source/elements/sh3n/coque3n/c3forc3.F
  engine/source/elements/shell/coqueba/cbaforc3.F
Labels: bug, engine, important

#3154 correction of non initialized parameter dtfactherm
  engine/source/engine/radioss2.F
  engine/source/input/freform.F
  engine/source/output/restart/rdresb.F
Labels: bug, engine, important

#3163 INIVOL 2d : manage superellipse and infinite plane with polygonal clipping method
  starter/share/modules1/inivol_mod.F
  starter/source/initial_conditions/inivol/ale_box_coloration.F
  starter/source/initial_conditions/inivol/hm_read_inivol.F90
  starter/source/initial_conditions/inivol/init_inivol.F90
  starter/source/initial_conditions/inivol/init_inivol_2D_polygons.F90
  starter/source/initial_conditions/inivol/inivol_set.F
  starter/source/initial_conditions/inivol/surface_min_max_computation.F
Labels: enhancement
