Repository OpenRadioss/OpenRadioss, pull requests merged in 2024-10, with the labels that each got.

#3028 restart file fix
  engine/source/interfaces/int22/w_bufbric_22.F
Labels: bug

#3034 correct division by zero error in m2law8.F
  engine/source/materials/mat/mat002/m2law8.F
Labels: bug, engine, important

#3036 input correction for law125 and law127 according to dyna input
  hm_cfg_files/config/CFG/radioss2025/MAT/matl125_laminated_composite.cfg
  hm_cfg_files/config/CFG/radioss2025/MAT/matl127_enhanced_composite.cfg
  starter/source/materials/mat/mat125/hm_read_mat125.F90
  starter/source/materials/mat/mat127/hm_read_mat127.F90
Labels: RFE, important

#3049 correction special case of RBE2 using local skew
  engine/source/constraints/general/rbe2/rbe2_imp0.F
  engine/source/constraints/general/rbe2/rbe2v.F
Labels: bug, important

#3052 /SET : 2D surface fix
  starter/source/model/sets/create_seg_clause.F
  starter/source/model/sets/fill_gr.F
  starter/source/model/sets/hm_set.F
Labels: bug, important

#3043 Add missing unit definition for Pmin in law2 cfg file
  hm_cfg_files/config/CFG/radioss2025/MAT/matl2_plas_johns.cfg
  starter/source/materials/mat/mat002/hm_read_mat02.F
Labels: bug, important

#3030 adjust stiffness of disortion control w/ law90
  engine/source/elements/solid/solide/s_hg5.F
  engine/source/elements/solid/solide/sforc3.F
  engine/source/elements/solid/solidez/shour_ctl.F90
  engine/source/elements/solid/solidez/szforc3.F
  engine/source/elements/solid/solidez/szhour_ctl.F
Labels: important

#3057 fix cfg error and change the starter file
  hm_cfg_files/config/CFG/radioss2025/MAT/matl127_enhanced_composite.cfg
  starter/source/materials/mat/mat127/hm_read_mat127.F90
  starter/source/output/message/starter_message_description.txt
Labels: bug, important

#3061 checking the numerical stability of composite material
  starter/source/materials/mat/mat122/hm_read_mat122.F
  starter/source/materials/mat/mat125/hm_read_mat125.F90
  starter/source/materials/mat/mat127/hm_read_mat127.F90
  starter/source/output/message/starter_message_description.txt
Labels: bug, enhancement, important

#3071 Issue in /H3D/NODA/CSE_FRIC option:
  engine/source/mpi/interfaces/spmd_i7tool.F
  engine/source/output/h3d/h3d_build_fortran/lech3d.F
Labels: bug, important

#3076 Error in c697016e4ef987aff9a825bc5e1899cfb7f366f6 :
  engine/source/output/h3d/h3d_build_fortran/lech3d.F
Labels: bug, important

#3078 correction mat125 non initialized value
  starter/source/materials/mat/mat125/hm_read_mat125.F90
Labels: important

#3064 add distortion control for thick shell elements
  engine/CMake_Compilers/legacy_fortran.cmake
  engine/source/elements/forint.F
  engine/source/elements/thickshell/solide6c/s6cforc3.F
  engine/source/elements/thickshell/solide6c/s6chour_ctl.F90
  engine/source/elements/thickshell/solide6c/s6for_distor.F90
  engine/source/elements/thickshell/solide6c/s6get_xv.F90
  engine/source/elements/thickshell/solide6c/sfor_visn6.F90
  engine/source/elements/thickshell/solide8c/s8cforc3.F
  engine/source/elements/thickshell/solidec/scforc3.F
  hm_cfg_files/config/CFG/radioss2025/PROP/prop_p20_tshell.cfg
  hm_cfg_files/config/CFG/radioss2025/PROP/prop_p21_tsh_orth.cfg
  hm_cfg_files/config/CFG/radioss2025/PROP/prop_p22_tsh_comp.cfg
  starter/source/elements/elbuf_init/elbuf_ini.F
  starter/source/elements/initia/initia.F
  starter/source/elements/solid/solide/sgrtails.F
  starter/source/properties/thickshell/hm_read_prop20.F
  starter/source/properties/thickshell/hm_read_prop21.F
  starter/source/properties/thickshell/hm_read_prop22.F
Labels: important

#3085 Correct of damage initialization in /fail/alter with Brokmann option
  starter/source/elements/initia/initia.F
  starter/source/elements/sh3n/coque3n/c3init3.F
  starter/source/elements/shell/coque/cinit3.F
  starter/source/elements/shell/coqueba/cbainit3.F
  starter/source/materials/fail/windshield_alter/brokmann_crack_init.F90
  starter/source/materials/fail/windshield_alter/brokmann_elem_spmd_renum.F90
  starter/source/materials/fail/windshield_alter/fail_windshield_init.F
  starter/source/starter/lectur.F
Labels: bug, starter, important

#3060 Law 169 : input cfg file and formulation change
  engine/source/elements/solid/sconnect/suser43.F
  engine/source/materials/mat/mat169/sigeps169_connect.F90
  hm_cfg_files/config/CFG/radioss2025/MAT/LAW169.cfg
  starter/source/materials/mat/mat169/hm_read_mat169.F90
Labels: RFE, important

#3086 correction error message introduced with law125
  starter/source/output/message/starter_message_description.txt
Labels: important

#3050 Correct thermal behavior of law4 without EOS and with linear EOS
  common_source/eos/eoslinear.F
  common_source/eos/eosmain.F
  engine/source/materials/mat/mat004/m4law.F
  engine/source/materials/mat_share/mmain.F90
  starter/source/materials/mat/mat004/hm_read_mat04.F
Labels: bug

#3097 Retractor fix + friction dc fix
  common_source/modules/seatbelt_mod.F
  engine/source/output/restart/rdresb.F
  engine/source/output/restart/wrrestp.F
  engine/source/tools/seatbelts/kine_seatbelt_force.F
  engine/source/tools/seatbelts/material_flow.F
  engine/source/user_interface/ufunc.F
  starter/source/restart/ddsplit/w_seatbelts.F
  starter/source/tools/seatbelts/hm_read_slipring.F
Labels: important

#3093 correction possible overflow in INISPHCEL when NUVAR > 0
  starter/source/starter/lectur.F
Labels: important

#3098 Bound damage value to 1 for /FAIL/JOHNSON
  engine/source/materials/fail/johnson_cook/fail_johnson.F
Labels: important

#3017 clean references to IPM parameters in viscosity models
  engine/source/materials/mat/mat069/sigeps69.F
  engine/source/materials/mat/mat069/sigeps69c.F
  engine/source/materials/mat_share/mulaw.F90
  engine/source/materials/mat_share/mulawc.F
  engine/source/materials/mat_share/usermat_shell.F
  engine/source/materials/mat_share/usermat_solid.F
  engine/source/materials/visc/prony_modelc.F
  engine/source/output/anim/generate/dfuncc_ply.F
  engine/source/output/anim/generate/genani.F
  engine/source/output/anim/generate/tensorc.F
  engine/source/output/anim/generate/tensorc_crk.F
  engine/source/output/anim/generate/tensorc_ply.F
  engine/source/output/dynain/dynain_c_strsg.F
  engine/source/output/dynain/gendynain.F
  engine/source/output/h3d/h3d_results/h3d_shell_tensor.F
  engine/source/output/sortie_main.F
  engine/source/output/th/thcoq.F
  starter/source/elements/solid/solide/sgrtails.F
  starter/source/materials/visc/hm_read_visc.F
  starter/source/spmd/domain_decomposition/initwg_solid.F
Labels: refactoring

#3102 Correct wrong material number in MAT_PARAM in thcoq.F
  engine/source/output/th/thcoq.F
Labels: bug, engine, important

#3103 Fix of warning message for joints
  starter/source/elements/joint/rjoint/rini45.F
Labels: important

#3104 TABLE FOR RETRACTORS
  common_source/modules/seatbelt_mod.F
  engine/source/engine/resol.F
  engine/source/output/restart/rdresb.F
  engine/source/output/restart/wrrestp.F
  engine/source/tools/seatbelts/material_flow.F
  engine/source/tools/seatbelts/retractor_table_inv.F90
  starter/source/output/message/starter_message_description.txt
  starter/source/restart/ddsplit/w_seatbelts.F
  starter/source/starter/lectur.F
  starter/source/tools/seatbelts/create_seatbelt.F
Labels: important

#3105 read *DATABASE_NODFOR & NCFORC dyna cards
  hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg
Labels: important

#3111 KJOINTS orientation fix
  starter/source/elements/joint/rjoint/rini45.F
Labels: important

#3110 update damage criteria printout in material law169
  engine/source/materials/mat/mat169/sigeps169_connect.F90
Labels: important

#3113 KJOINTS initial rotation fix
  starter/source/elements/joint/rjoint/rini45.F
Labels: important
