Repository OpenRadioss/OpenRadioss, pull requests merged in 2024-06, with the labels that each got.

#2735 Memory related issues in SeatBelts & Type2 interface:
  engine/source/interfaces/interf/i2for28_cin.F
  engine/source/interfaces/interf/i2for28p_cin.F
  engine/source/interfaces/interf/i2for3.F
  engine/source/interfaces/interf/i2for3p.F
  engine/source/interfaces/interf/intti1.F
  engine/source/output/h3d/h3d_build_fortran/lech3d.F
  engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F
  engine/source/output/h3d/h3d_results/h3d_shell_tensor.F
  engine/source/output/restart/wrrestp.F
  engine/source/tools/seatbelts/kine_seatbelt_force.F
Labels: bug, important

#2720 support offset for standard shell /PROP/TYPE1,9,10
  engine/source/elements/shell/coque/layini.F
  engine/source/interfaces/shell_offset/inter_offset_ini.F90
  engine/source/materials/mat_share/cmain3.F
  engine/source/materials/mat_share/mulawc.F
  engine/source/materials/mat_share/mulawglc.F
  hm_cfg_files/config/CFG/radioss2024/PROP/prop_p10_sh_comp.cfg
  hm_cfg_files/config/CFG/radioss2024/PROP/prop_p1_shell.cfg
  hm_cfg_files/config/CFG/radioss2024/PROP/prop_p9_sh_orth.cfg
  starter/source/elements/shell/coque/cinmas.F
  starter/source/elements/shell/shell_offset/chk_shell_offset.F90
  starter/source/elements/shell/shell_offset/dim_shell_offsetp.F90
  starter/source/elements/shell/shell_offset/shell_offset_ini.F90
  starter/source/elements/shell/shell_offset/shell_offsetp.F90
  starter/source/properties/shell/hm_read_prop01.F
  starter/source/properties/shell/hm_read_prop09.F
  starter/source/properties/shell/hm_read_prop10.F
  starter/source/properties/shell/hm_read_prop16.F
  starter/source/starter/lectur.F
Labels: important

#2738 Correct H3D and ANIM output of total strain in law58
  engine/source/materials/mat/mat058/sigeps58c.F
  engine/source/output/anim/generate/dfuncc.F
  engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F
Labels: bug, important

#2733 Correction of numerical singularity in material law83
  engine/source/materials/mat/mat083/sigeps83.F
Labels: bug, important

#2737 Add non-local regularization to /MAT/LAW126
  engine/source/materials/mat/mat126/sigeps126.F90
  engine/source/materials/mat_share/mulaw.F
  starter/source/materials/mat/mat126/hm_read_mat126.F90
Labels: important

#2741 /INTER/TYPE18 bug fix: undefined behavior
  engine/source/engine/resol.F
  engine/source/interfaces/int18/int18_alloc.F
Labels: bug, important

#2742 fix bug /STATE/SHELL/../GLOBAL option
  engine/source/output/dynain/dynain_c_strag.F
  engine/source/output/dynain/dynain_c_strsg.F
  engine/source/output/sta/stat_c_strafg.F
  engine/source/output/sta/stat_c_strsfg.F
  engine/source/output/sty/c_tf_ne.F
Labels: bug, important

#2740 make Parith/on available for shell offset supporting contact
  engine/CMake_Compilers/legacy_fortran.cmake
  engine/source/engine/resol.F
  engine/source/engine/resol_init.F
  engine/source/interfaces/shell_offset/inter_offset_ini.F90
  engine/source/interfaces/shell_offset/offset_nproj.F90
  engine/source/modules/interfaces/sh_offset_mod.F90
  engine/source/mpi/nodes/spmd_exch_vnpon.F90
Labels: important

#2744 correction of gap values in interface type21 Starter to avoid wrong i…
  starter/source/interfaces/inter3d1/i21gap3.F
  starter/source/interfaces/inter3d1/inint3_thkvar.F
Labels: bug, important

#2726 /INIVOL : code refactoring + initialization bug
  engine/share/includes/com04_c.inc
  starter/CMake_Compilers/legacy_fortran.cmake
  starter/share/includes/tabsiz_c.inc
  starter/share/modules1/inivol_mod.F
  starter/source/coupling/rad2rad/r2r_group.F
  starter/source/coupling/rad2rad/r2r_prelec.F
  starter/source/elements/initia/initia.F
  starter/source/elements/solid/solide/sgrtails.F
  starter/source/elements/solid_2d/quad/qgrtails.F
  starter/source/elements/solid_2d/tria/t3grtails.F
  starter/source/initial_conditions/inivol/ale_box_coloration.F
  starter/source/initial_conditions/inivol/ale_box_creation.F
  starter/source/initial_conditions/inivol/ale_element_size_computation.F
  starter/source/initial_conditions/inivol/getphase.F
  starter/source/initial_conditions/inivol/hm_read_inivol.F
  starter/source/initial_conditions/inivol/inifill.F
  starter/source/initial_conditions/inivol/iniphase.F
  starter/source/initial_conditions/inivol/inisoldist.F
  starter/source/initial_conditions/inivol/init_inivol.F90
  starter/source/initial_conditions/inivol/inivol_set.F
  starter/source/initial_conditions/inivol/mean_node_norm2.F
  starter/source/initial_conditions/inivol/nfacette.F
  starter/source/initial_conditions/inivol/phase_detection.F
  starter/source/initial_conditions/inivol/ratio_fill.F
  starter/source/initial_conditions/inivol/surface_min_max_computation.F
  starter/source/materials/mat/mat151/hm_read_mat151.F
  starter/source/output/qaprint/st_qaprint_inivol.F
  starter/source/starter/contrl.F
  starter/source/starter/lectur.F
Labels: refactoring

#2748 remove Ioffset=3 for shell offset
  engine/source/interfaces/shell_offset/offset_nproj.F90
  hm_cfg_files/config/CFG/radioss2024/CARDS/def_shell.cfg
  starter/source/general_controls/default_values/hm_read_defshell.F
Labels: important

#2745 Restart Read & Write refactoring in Engine:
  common_source/modules/output/anim_mod.F
  engine/share/modules/stack_mod.F
  engine/source/engine/radioss2.F
  engine/source/engine/resol.F
  engine/source/engine/resol_head.F
  engine/source/output/restart/arralloc.F
  engine/source/output/restart/rdresb.F
  engine/source/output/restart/wrrest.F
  engine/source/output/restart/wrrestp.F
Labels: refactoring

#2753 issue correction in box cylinder : check for node inside or outside was incorrect
  starter/source/model/box/rdbox.F
Labels: important

#2754 Bug in commit: db6846f78e35109dd05011d70bd48ba1af81c11d with rad2rad
  engine/source/engine/resol.F
Labels: bug

#2760 multidomains : correction of MATPARAM copy between subdomains
  starter/source/elements/elbuf_init/r2r_matparam_copy.F
Labels: bug, starter, important

#2761 /EBCS/INLET : compatibility with SUBMODELING (//SUBMODEL)
  starter/source/boundary_conditions/ebcs/hm_read_ebcs_inlet.F
  starter/source/boundary_conditions/ebcs/read_ebcs.F
Labels: bug

#2763 /LOAD/PFLUID:update for parallel arithmetic OFF
  engine/source/engine/resol.F
  engine/source/loads/general/pfluid/pfluid.F
Labels: bug

#2769 Fix soundspeed computation for /MAT/LAW66 in case of specific Young modulus in compression
  engine/source/materials/mat/mat066/sigeps66.F
Labels: important
