Repository OpenRadioss/OpenRadioss, pull requests merged in 2024-09, with the labels that each got.

#2947 Issue in User Properties (using in user libraries) :
  engine/source/user_interface/suforc3.F
  starter/source/elements/elbuf_init/suinit3.F
Labels: bug, important

#2969 INIVOL / LAW51 : bug fix
  starter/source/initial_conditions/inivol/inivol_set.F
  starter/source/materials/mat/mat051/hm_read_mat51.F
Labels: bug

#2983 issue creating surface from 3 node shells in /SET mechanism
  starter/source/model/sets/shell_surface_buffer_remesh.F
Labels: bug

#2993 Correct implicit code with law42 after parameter storage refactoring
  engine/source/elements/solid/solide8z/mmats.F
Labels: bug, engine

#2988 enhancement of solid and shell material law
  engine/source/materials/mat/mat125/sigeps125.F90
  engine/source/materials/mat/mat125/sigeps125c.F90
  engine/source/materials/mat/mat127/sigeps127c.F90
  engine/source/materials/mat_share/mulaw.F90
  engine/source/materials/mat_share/mulawc.F
  hm_cfg_files/config/CFG/radioss2024/data_hierarchy.cfg
  hm_cfg_files/config/CFG/radioss2025/MAT/matl125_laminated_composite.cfg
  hm_cfg_files/config/CFG/radioss2025/MAT/matl127_enhanced_composite.cfg
  hm_cfg_files/config/CFG/radioss2025/data_hierarchy.cfg
  starter/source/elements/initia/initia.F
  starter/source/elements/shell/coque/set_elgroup_param.F
  starter/source/materials/mat/hm_read_mat.F
  starter/source/materials/mat/mat125/hm_read_mat125.F90
  starter/source/materials/mat/mat127/hm_read_mat127.F90
Labels: enhancement, important

#3019 Correct strain rate TH output for material law 83
  engine/source/output/th/thsol.F
Labels: bug, engine
