Repository OpenRadioss/OpenRadioss, pull requests merged in 2024-12, with the labels that each got.

#3173 INIVOL (2D) : compatibility with ordered list of nodes
  hm_cfg_files/config/CFG/radioss2025/TABLE/inivol.cfg
  starter/share/modules1/inivol_mod.F
  starter/source/elements/initia/initia.F
  starter/source/initial_conditions/inivol/hm_read_inivol.F90
  starter/source/initial_conditions/inivol/init_inivol.F90
  starter/source/initial_conditions/inivol/init_inivol_2D_polygons.F90
  starter/source/output/message/starter_message_description.txt
  starter/source/starter/lectur.F
Labels: enhancement

#3172 new thermal models parameter storage structure under mat_param
  common_source/modules/mat_elem/matparam_def_mod.F90
  common_source/modules/mat_elem/therm_param_mod.F90
  engine/source/output/restart/read_matparam.F
  engine/source/output/restart/read_thermparam.F90
  engine/source/output/restart/write_matparam.F
  engine/source/output/restart/write_thermparam.F90
  starter/source/elements/elbuf_init/r2r_matparam_copy.F
  starter/source/materials/mat/hm_read_mat.F90
  starter/source/materials/mat/ini_mat_elem.F
  starter/source/materials/mat/write_matparam.F
  starter/source/materials/mat/write_thermparam.F90
  starter/source/materials/read_material_models.F
  starter/source/materials/therm/hm_read_therm.F
  starter/source/materials/therm/hm_read_therm_stress.F
  starter/source/materials/therm/hm_read_therm_stress.F90
  starter/source/restart/ddsplit/ddsplit.F
  starter/source/starter/lectur.F
Labels: refactoring

#3208 Windows compiler issue
  engine/source/elements/solid/solide4_sfem/s4voln_m.F
Labels: bug
