Repository OpenRadioss/OpenRadioss, pull requests merged in 2024-07, with the labels that each got.

#2784 correction MOVE_FUNC + TABLE option with negative x scale factor
  starter/source/tools/curve/hm_read_move_funct.F
Labels: bug, important

#2789 bug fix for splipring (SPMD)
  starter/source/spmd/domain_decomposition/c_domain_decomposition.cpp
Labels: important

#2788 NEW INIVOL 2D METHOD (POLYGON CLIPPING)
  common_source/tools/clipping/polygon_clipping_mod.F90
  common_source/tools/clipping/polygon_mod.F90
  common_source/tools/sort/array_reindex.F90
  common_source/tools/sort/insertion_sort.F90
  engine/source/interfaces/int22/i22clip_tools.F
  starter/share/modules1/inivol_mod.F
  starter/source/elements/initia/initia.F
  starter/source/initial_conditions/inivol/ale_box_coloration.F
  starter/source/initial_conditions/inivol/connesurf.F
  starter/source/initial_conditions/inivol/hm_read_inivol.F
  starter/source/initial_conditions/inivol/inisoldist.F
  starter/source/initial_conditions/inivol/init_inivol.F90
  starter/source/initial_conditions/inivol/init_inivol_2D_polygons.F90
  starter/source/initial_conditions/inivol/inivol_set.F
  starter/source/initial_conditions/inivol/ratio_fill.F
  starter/source/initial_conditions/inivol/surface_min_max_computation.F
  starter/source/output/message/starter_message_description.txt
  starter/source/starter/lectur.F
Labels: enhancement

#2821 fix Nan issue when isotropic law used in Prop/type51 in the ply
  engine/source/elements/sh3n/coquedk/cncoef3.F
  engine/source/elements/shell/coquez/czforc3.F
  engine/source/elements/xfem/czforc3_crk.F
Labels: bug, important

#2823 intialization of variable
  engine/source/elements/sh3n/coquedk/cncoef3.F
Labels: bug, important

#2831 fix bug when we use /PROP/TYPE11 or 17 with QEPH and Isotropic law in the ply
  engine/source/elements/sh3n/coquedk/cncoef3.F
Labels: bug, important

#2836 /MAT/LAW36 : compatibility with /EOS
  engine/source/materials/mat/mat036/sigeps36.F
  engine/source/materials/mat_share/mulaw.F90
  engine/source/materials/mat_share/mulaw8.F
  starter/source/materials/mat/mat036/hm_read_mat36.F
  starter/source/materials/mat/mat044/hm_read_mat44.F
Labels: RFE

#2771 translate material and element structure modules to F90 format
  common_source/modules/mat_elem/elbufdef_mod.F
  common_source/modules/mat_elem/elbufdef_mod.F90
  common_source/modules/mat_elem/fail_param_mod.F
  common_source/modules/mat_elem/fail_param_mod.F90
  common_source/modules/mat_elem/group_param_mod.F
  common_source/modules/mat_elem/group_param_mod.F90
  common_source/modules/mat_elem/mat_elem_mod.F
  common_source/modules/mat_elem/mat_elem_mod.F90
  common_source/modules/mat_elem/matparam_def_mod.F
  common_source/modules/mat_elem/matparam_def_mod.F90
  common_source/modules/mat_elem/ply_param_mod.F
  common_source/modules/mat_elem/ply_param_mod.F90
  common_source/modules/mat_elem/prop_param_mod.F
  common_source/modules/mat_elem/prop_param_mod.F90
  common_source/modules/mat_elem/visc_param_mod.F
  common_source/modules/mat_elem/visc_param_mod.F90
Labels: refactoring
