Repository OpenRadioss/OpenRadioss, pull requests merged in 2024-08, with the labels that each got.

#2879 /MAT/LAW42 : allow new input with 10 Ogden model terms instead of 5
  engine/source/materials/mat/mat042/sigeps42.F
  engine/source/materials/mat/mat042/sigeps42c.F
  engine/source/materials/mat_share/mulaw.F90
  engine/source/materials/mat_share/mulaw8.F
  engine/source/materials/mat_share/mulawc.F
  hm_cfg_files/config/CFG/radioss2025/MAT/matl42_Ogden.cfg
  starter/source/elements/sh3n/coque3n/c3derii.F
  starter/source/elements/sh3n/coquedk/cdkderii.F
  starter/source/elements/shell/coque/cdleni.F
  starter/source/elements/shell/coqueba/cndleni.F
  starter/source/materials/mat/hm_read_mat.F
  starter/source/materials/mat/mat042/hm_read_mat42.F
  starter/source/materials/mat/mat042/law42_upd.F
  starter/source/materials/mat/mat042/sigeps42.F
  starter/source/materials/mat_share/mulaw.F
  starter/source/materials/updmat.F
Labels: enhancement, RFE

#2897 H3D and QUAD : fix
  engine/source/output/h3d/h3d_results/h3d_quad_scalar_1.F90
Labels: bug

#2901 /INTER/TYPE1: Bug Fix for 2D Analysis
  starter/source/interfaces/inter2d1/inint2.F
  starter/source/interfaces/inter3d1/inint3.F
Labels: bug

#2880 /MAT/LAW02 : add compatibility with /EOS option
  engine/source/materials/mat/mat002/m2law.F
  engine/source/materials/mat_share/mmain.F90
  starter/source/materials/mat/mat002/hm_read_mat02.F
Labels: RFE

#2899 lprony + iform=1 and law 42 don't working correctly
  starter/source/materials/mat/mat042/law42_upd.F
Labels: bug

#2895 scr17_c.inc : cursor cleaning (direct reader(old one))
  common_source/modules/element_user_id.F90
  engine/source/output/restart/rdcomm.F
  engine/source/output/restart/wrcomm.F
  starter/share/includes/scr17_c.inc
  starter/share/modules1/reader_old_mod.F90
  starter/share/modules1/refsta_mod.F
  starter/source/coupling/rad2rad/lecextlnk.F
  starter/source/coupling/rad2rad/r2r_group.F
  starter/source/coupling/rad2rad/r2r_input.F
  starter/source/coupling/rad2rad/r2r_prelec.F
  starter/source/coupling/rad2rad/routines_r2r.F
  starter/source/elements/ige3d/lecig3d.F
  starter/source/elements/ige3d/nbadigemesh.F
  starter/source/elements/ige3d/prelecig3d.F
  starter/source/elements/initia/lec_inistate_tri.F
  starter/source/elements/reader/hm_preread_node.F
  starter/source/elements/reader/hm_read_beam.F
  starter/source/elements/reader/hm_read_node.F
  starter/source/elements/reader/hm_read_quad.F
  starter/source/elements/reader/hm_read_rivet.F
  starter/source/elements/reader/hm_read_sh3n.F
  starter/source/elements/reader/hm_read_shell.F
  starter/source/elements/reader/hm_read_solid.F
  starter/source/elements/reader/hm_read_sphcel.F
  starter/source/elements/reader/hm_read_spring.F
  starter/source/elements/reader/hm_read_tria.F
  starter/source/elements/reader/hm_read_truss.F
  starter/source/general_controls/computation/hm_read_unit.F
  starter/source/groups/hm_read_lines.F
  starter/source/groups/hm_read_surfsurf.F
  starter/source/initial_conditions/inista/lec_inistate_yfile.F
  starter/source/initial_conditions/inista/yctrl.F
  starter/source/interfaces/friction/reader/hm_read_friction_models.F
  starter/source/interfaces/int24/hm_read_inter_type24.F
  starter/source/loads/general/grav/hm_read_grav.F
  starter/source/loads/laser/leclas.F
  starter/source/loads/reference_state/refsta/lecrefsta.F
  starter/source/materials/mat/hm_read_mat.F
  starter/source/materials/mat/mat010/hm_read_mat10.F
  starter/source/materials/mat/mat026/hm_read_mat26.F
  starter/source/materials/mat/matuser/hm_read_mat_user29_31.F
  starter/source/materials/mat/matuser/hm_read_mat_user_99.F
  starter/source/model/assembling/hm_read_submodel.F
  starter/source/model/box/bigbox.F
  starter/source/model/remesh/admlist.F
  starter/source/model/remesh/build_admesh.F
  starter/source/model/remesh/nbadmesh.F
  starter/source/output/cluster/hm_read_cluster.F
  starter/source/output/th/hm_read_thgrou.F
  starter/source/output/th/hm_thgrki_vent.F
  starter/source/properties/hm_read_prop_generic.F
  starter/source/restart/ddsplit/wrcommp.F
  starter/source/spmd/domain_decomposition/grid2mat.F
  starter/source/starter/freform.F
  starter/source/starter/lectur.F
  starter/source/starter/starter0.F
  starter/source/tools/curve/hm_read_table.F
  starter/source/tools/sensor/read_sensor_user.F
  starter/source/user_interface/user_output.F
Labels: refactoring

#2882 Update mat_param structure adding elastic stiffness constants
  common_source/modules/mat_elem/matparam_def_mod.F90
  engine/source/output/restart/read_matparam.F
  engine/source/output/restart/write_matparam.F
  starter/source/elements/elbuf_init/r2r_matparam_copy.F
  starter/source/materials/mat/hm_read_mat.F
  starter/source/materials/mat/ini_mat_elem.F
  starter/source/materials/mat/write_matparam.F
Labels: refactoring

#2915 /H3D : bug fix for QUAD elements and vectors output
  engine/source/output/h3d/h3d_results/h3d_quad_vector.F
Labels: bug

#2919 /INIVOL enhancement : default submat is the prevalent one
  common_source/modules/constant_mod.F
  starter/source/initial_conditions/inivol/hm_read_inivol.F
  starter/source/initial_conditions/inivol/iniphase.F
  starter/source/initial_conditions/inivol/inivol_set.F
Labels: enhancement

#2924 H3D : update for QUADS
  engine/source/output/anim/generate/output_schlieren.F
  engine/source/output/anim/generate/schlieren_buffer_gathering.F
  engine/source/output/h3d/h3d_results/h3d_quad_scalar.F
  engine/source/output/h3d/h3d_results/h3d_quad_scalar_1.F90
  engine/source/output/h3d/h3d_results/h3d_solid_scalar_1.F
Labels: bug

#2928 correct bug in element buffer initialization for beams with failure
  starter/source/elements/elbuf_init/elbuf_ini.F
Labels: bug, starter

#2930 rigid wall, fix SPMD regression from 4395dc6
  starter/source/constraints/general/rwall/split_rwall.F90
Labels: bug

#2934 Correction of material law weight calculation with /visc/prony
  starter/source/spmd/domain_decomposition/initwg_shell.F
  starter/source/spmd/domain_decomposition/initwg_tri.F
Labels: bug, starter
