Repository OpenRadioss/OpenRadioss, pull requests merged in 2025-05, with the labels that each got.

#3670 /MAT/LAW133 (GRANULAR) : new material law
  engine/share/modules/debug_mod.F
  engine/source/engine/resol.F
  engine/source/materials/mat/mat010/m10law.F
  engine/source/materials/mat/mat021/m21law.F
  engine/source/materials/mat/mat133/sigeps133.F90
  engine/source/materials/mat_share/mmain.F90
  engine/source/materials/mat_share/mulaw.F90
  engine/source/materials/tools/table_mat_vinterp.F
  engine/source/output/anim/generate/dfunc6.F
  engine/source/output/th/thsol.F
  hm_cfg_files/config/CFG/radioss2026/MAT/matl133.cfg
  hm_cfg_files/config/CFG/radioss2026/data_hierarchy.cfg
  starter/source/materials/mat/hm_read_mat.F90
  starter/source/materials/mat/mat010/hm_read_mat10.F
  starter/source/materials/mat/mat021/hm_read_mat21.F
  starter/source/materials/mat/mat049/hm_read_mat49.F
  starter/source/materials/mat/mat133/hm_read_mat133.F90
  starter/source/materials/mat/mat133/law133_upd.F90
  starter/source/materials/updmat.F
  starter/source/output/anim/dfuncs.F
  starter/source/output/message/inimsg.F
  starter/source/output/message/starter_message_description.txt
Labels: enhancement

#3692 Correct strain output in ANIM for the composite shells with layer position offset
  engine/source/output/anim/generate/genani.F
  engine/source/output/anim/generate/tensorc.F
  engine/source/output/h3d/h3d_results/h3d_shell_tensor.F
  engine/source/output/sortie_main.F
Labels: bug, engine

#3695 Correct allocation/deallocation problem in ANIM tensor output
  engine/source/output/anim/generate/tensorc.F
Labels: bug, engine, important

#3755 /MAT/LAW10 : eos buffer allocation with embedded eos
  common_source/modules/mat_elem/eos_param_mod.F90
  starter/source/materials/eos/hm_read_eos_powderburn.F90
  starter/source/materials/mat/mat010/hm_read_mat10.F
Labels: bug

#3775 group creation issue when referencing engine keywords with comments
  starter/source/model/sets/fill_igr.F
Labels: bug
