Repository OpenRadioss/OpenRadioss, pull requests merged in 2025-06, with the labels that each got.

#3776 /INTER/TYPE18 + /MAT/LAW151 + SPMD : starter voxel search fix
  common_source/interf/int18_law151_nsv_shift.F
  common_source/modules/ale/multi_fvm_mod.F90
  engine/source/interfaces/int18/int18_law151_nsv_shift.F
  engine/source/interfaces/interf/intfop2.F
  engine/source/interfaces/intsort/inttri.F
  starter/source/interfaces/int18/int18_law151_alloc.F
  starter/source/interfaces/inter3d1/i7buc_vox1.F
  starter/source/interfaces/inter3d1/i7sti3.F
  starter/source/interfaces/inter3d1/i7trivox1.F
  starter/source/interfaces/inter3d1/inint3.F
  starter/source/interfaces/interf1/inintr.F
Labels: bug

#3793 enhancement of law125 + update cfg file for input 2026
  engine/source/materials/mat/mat125/sigeps125c.F90
  engine/source/materials/mat_share/mulawc.F90
  hm_cfg_files/config/CFG/radioss2025/data_hierarchy.cfg
  hm_cfg_files/config/CFG/radioss2026/MAT/matl125_laminated_composite.cfg
  hm_cfg_files/config/CFG/radioss2026/MAT/matl127_enhanced_composite.cfg
  hm_cfg_files/config/CFG/radioss2026/data_hierarchy.cfg
  starter/source/materials/mat/mat125/hm_read_mat125.F90
Labels: RFE

#3813 Correct wrong test of lagrangian formulation in law2 for shells
  engine/source/materials/mat/mat002/sigeps02c.F
  engine/source/materials/mat_share/mulawc.F90
Labels: bug, engine

#3825 correct non initialized element temperature in 16 and 20 node solids …and thickshells
  starter/source/elements/solid/solide20/s20init3.F
  starter/source/elements/thickshell/solide16/s16init3.F
Labels: bug, starter

#3836 Correct function treatment in law70 with multiple unloading curves
  starter/source/materials/mat/mat070/hm_read_mat70.F
Labels: bug, starter

#3845 fix the difference of shear behavior against Dyna
  engine/source/materials/mat/mat066/sigeps66.F
  engine/source/materials/mat/mat066/sigeps66c.F
Labels: bug

#3868 Correct the total strain calculation in law24
  engine/source/materials/mat/mat024/conc24.F
  starter/source/elements/solid/solide/sgrtails.F
Labels: bug
