Repository OpenRadioss/OpenRadioss, pull requests merged in 2025-09, with the labels that each got.

#4108 Multimaterial Solver law 151 : Tillotson EoS fix
  common_source/eos/tillotson.F
Labels: bug, important

#4126 RAD2RAD fix
  common_source/modules/multimat_param_mod.F90
  starter/source/elements/elbuf_init/r2r_matparam_copy.F
Labels: important

#4128 FIx of warning message for computation of skew for springs
  starter/source/elements/spring/r4buf3.F
Labels: important

#4134 Bug correction in hm_read_impflux
  starter/source/constraints/thermic/hm_read_impflux.F
Labels: bug, starter, important

#4133 *AIRBAG_HYBRID: read and convert to /MONVOL/COMMU1
  hm_cfg_files/config/CFG/Keyword971_R14.1/CONTROL_VOLUME/subobj_airbag_hybrid.cfg
  hm_cfg_files/config/CFG/Keyword971_R14.1/data_hierarchy.cfg
  hm_cfg_files/config/CFG/Keyword971_R8.0/CONTROL_VOLUME/airbag_option.cfg
Labels: important

#4135 Correct NAN bug when writing STA file in engine
  engine/source/output/sta/stat_size.F
Labels: bug, important
