Repository OpenRadioss/OpenRadioss, pull requests merged in 2025-03, with the labels that each got.

#3477 /HEAT/MAT : fix NEL issue for ALE
  engine/source/ale/alemain.F
  engine/source/ale/alethe.F
  engine/source/ale/atherm.F
Labels: bug

#3485 Add multiple checks to detect input errors in /TABLE definitions
  starter/source/materials/tools/table_values_2d.F
  starter/source/output/message/starter_message_description.txt
  starter/source/tools/curve/fnv1a_checksum.cpp
  starter/source/tools/curve/fnv1a_checksum_mod.F90
  starter/source/tools/curve/hm_read_table2_1.F
Labels: enhancement, starter

#3492 Correction of thermal options problem with adaptative meshing
  engine/source/model/remesh/admdiv.F
  engine/source/model/remesh/admfor0.F
  engine/source/model/remesh/admregul.F
  engine/source/model/remesh/admvit.F
Labels: bug

#3533 SEATBELT - Fix of Mat114 + contact for 2Dseatbelt
  engine/source/tools/seatbelts/redef_seatbelt.F90
  engine/source/tools/seatbelts/update_slipring.F
Labels: important

#3513 DAMPINF_FREQ_RANGE for shells
  engine/source/general_controls/damping/damping_range_shell.F90
  engine/source/general_controls/damping/damping_range_shell_mom.F90
  engine/source/materials/mat_share/cmain3.F
  engine/source/materials/mat_share/mulawc.F90
  engine/source/materials/mat_share/mulawglc.F
  engine/source/materials/visc/prony_modelc.F
  starter/source/elements/elbuf_init/elbuf_ini.F
  starter/source/elements/sh3n/coque3n/c3grhead.F
  starter/source/elements/sh3n/coque3n/c3grtails.F
  starter/source/elements/shell/coque/cgrhead.F
  starter/source/elements/shell/coque/cgrtails.F
  starter/source/starter/lectur.F
Labels: important

#3539 adding frequency independent damping using /VISC/PLAS
  engine/source/materials/mat_share/mmain.F90
  engine/source/materials/mat_share/mulaw.F90
  engine/source/materials/mat_share/usermat_solid.F
  engine/source/materials/visc/visc_plas.F90
  engine/source/materials/visc/viscmain.F
  hm_cfg_files/config/CFG/radioss2025/MAT/mat_VISC_PLAS.cfg
  hm_cfg_files/config/CFG/radioss2025/data_hierarchy.cfg
  starter/source/elements/elbuf_init/elbuf_ini.F
  starter/source/materials/visc/hm_read_visc.F
  starter/source/materials/visc/hm_read_visc_plas.F90
Labels: important

#3545 /FUNCT/PYTHON libpython opened with RTLD_GLOBAL
  common_source/modules/cpp_python_funct.cpp
Labels: important

#3562 regression for #3264: name mismatch in deallocation of PON structure
  engine/source/engine/resol.F
Labels: bug, important

#3552 New Keyword FAILIP for all the failure criterias in intergrated beam
  engine/source/elements/beam/fail_beam18.F
  engine/source/materials/fail/biquad/fail_biquad_ib.F
  engine/source/materials/fail/cockroft_latham/fail_cockroft_ib.F
  engine/source/materials/fail/energy/fail_energy_ib.F
  engine/source/materials/fail/gene1/fail_gene1_ib.F90
  engine/source/materials/fail/johnson_cook/fail_johnson_ib.F
  engine/source/materials/fail/tensstrain/fail_tensstrain_ib.F
  hm_cfg_files/config/CFG/radioss2025/FAIL/fail_biquad.cfg
  hm_cfg_files/config/CFG/radioss2025/FAIL/fail_cockcroft.cfg
  hm_cfg_files/config/CFG/radioss2025/FAIL/fail_energy.cfg
  hm_cfg_files/config/CFG/radioss2025/FAIL/fail_gene1.cfg
  hm_cfg_files/config/CFG/radioss2025/FAIL/fail_johnson.cfg
  hm_cfg_files/config/CFG/radioss2025/FAIL/fail_tensstrain.cfg
  starter/source/materials/fail/biquad/hm_read_fail_biquad.F
  starter/source/materials/fail/cockroft_latham/hm_read_fail_cockcroft.F
  starter/source/materials/fail/energy/hm_read_fail_energy.F
  starter/source/materials/fail/gene1/hm_read_fail_gene1.F
  starter/source/materials/fail/johnson_cook/hm_read_fail_johnson.F
  starter/source/materials/fail/tensstrain/hm_read_fail_tensstrain.F
Labels: important

#3568 /INTER/TYPE18 : updating configuration file for the Reader
  hm_cfg_files/config/CFG/radioss2022/INTER/inter_type18.cfg
  starter/source/interfaces/int18/hm_read_inter_type18.F
Labels: important

#3567 Change checksum routine algorithm for input error detection in /TABLE/1
  common_source/tools/sort/myqsort_d.F90
  starter/source/tools/curve/hm_read_table2_1.F
  starter/source/tools/curve/simple_checksum.cpp
  starter/source/tools/curve/simple_checksum_mod.F90
Labels: bug, starter

#3575 R2D : Reader update due to fix in CFG file
  starter/source/coupling/rad2rad/r2r_prelec.F
Labels: important

#3579 /H3D/ELEM/TDET + LAW 151 + TRIA (2d) : detonation times output
  engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F
Labels: important

#3573 Possible failure with /ANIM/VECT/PCONT whit tetra10
  engine/source/output/anim/generate/ani_pcont.F
Labels: important

#3572 /LOAD/PBLAST : zeroing output data structure
  starter/source/loads/pblast/hm_read_pblast.F
Labels: important

#3574 Regressions in /FUNCT_PYTHON
  common_source/modules/cpp_python_funct.cpp
  common_source/modules/cpp_python_funct.h
  common_source/modules/python_mod.F90
  engine/source/elements/spring/r26sig.F
  engine/source/elements/spring/r27def3.F
  engine/source/elements/spring/redef3.F90
  engine/source/engine/resol.F
  engine/source/tools/seatbelts/redef_seatbelt.F90
  starter/source/starter/lectur.F
  starter/source/tools/sensor/hm_read_sensor_python.F90
Labels: important

#3571 change the declaration of variable
  engine/source/materials/visc/viscmain.F
Labels: important

#3581 Correct yield stress calculation in law128 for hourglass in case of kinematic hardening
  engine/source/materials/mat/mat128/sigeps128c.F90
  engine/source/materials/mat/mat128/sigeps128s.F90
Labels: bug, engine, important

#3566 /ALE/GRID/LAGRANGE : ALE solver with lagrange framework (grid control)
  engine/source/ale/grid/alew7.F
  engine/source/ale/grid/alew8.F90
  engine/source/ale/grid/alewdx.F
  engine/source/input/freform.F
  engine/source/input/lectur.F
  hm_cfg_files/config/CFG/radioss2025/CARDS/ale_grid_lagrange.cfg
  hm_cfg_files/config/CFG/radioss2025/data_hierarchy.cfg
  starter/source/general_controls/ale_grid/hm_read_ale_grid.F
Labels: enhancement

#3524 change default value of dm (memebrane damping) of law1,2,22 for QEPH shell element
  common_source/modules/mat_elem/elbufdef_mod.F90
  engine/source/elements/elbuf/allocbuf_auto.F
  engine/source/elements/elbuf/w_elbuf_str.F
  engine/source/elements/sh3n/coque3n/c3forc3.F
  engine/source/elements/sh3n/coquedk/cdkforc3.F
  engine/source/elements/sh3n/coquedk6/cdk6forc3.F
  engine/source/elements/shell/coque/cforc3.F
  engine/source/elements/shell/coqueba/cbaforc3.F
  engine/source/elements/shell/coquez/czforc3.F
  engine/source/elements/xfem/c3forc3_crk.F
  engine/source/elements/xfem/cforc3_crk.F
  engine/source/elements/xfem/czforc3_crk.F
  engine/source/materials/mat_share/cmain3.F
  engine/source/materials/mat_share/mulawglc.F
  qa-tests/miniqa/SMOKE_TEST/data/ref.extract
  qa-tests/miniqa/SMOKE_TEST/reference/TWISBEAMA001.gz
  qa-tests/miniqa/SMOKE_TEST/reference/TWISBEAMA003.gz
  qa-tests/miniqa/SMOKE_TEST/reference/TWISBEAMT01
  qa-tests/miniqa/SMOKE_TEST/reference/TWISBEAM_0000.out
  qa-tests/miniqa/SMOKE_TEST/reference/TWISBEAM_0001.out
  starter/source/elements/elbuf_init/allocbuf_auto.F
  starter/source/elements/elbuf_init/elbuf_ini.F
  starter/source/elements/elbuf_init/zerovars_auto.F
  starter/source/elements/shell/coque/set_elgroup_param.F
  starter/source/restart/ddsplit/w_elbuf_str.F
Labels: important
