Repository OpenRadioss/OpenRadioss, pull requests merged in 2025-07, with the labels that each got.

#3932 /H3D/NODA/PEXT, /ANIM/NODA/PEXT : output External Pressure at mesh Nodes
  common_source/modules/output/output_mod.F90
  engine/source/engine/resol.F
  engine/source/loads/pblast/pblast_1.F
  engine/source/loads/pblast/pblast_2.F
  engine/source/loads/pblast/pblast_3.F
  engine/source/output/anim/generate/genani.F
  engine/source/output/anim/reader/anim_dcod_key_0.F
  engine/source/output/anim/reader/freanim.F
  engine/source/output/h3d/h3d_build_fortran/h3d_read.F
  engine/source/output/h3d/h3d_build_fortran/lech3d.F
  engine/source/output/h3d/h3d_results/h3d_nodal_scalar.F
  engine/source/output/h3d/input_list/h3d_gene_keyword.F
  engine/source/output/h3d/input_list/h3d_list_noda_scalar.F
  engine/source/output/restart/rdcomm.F
  engine/source/output/restart/wrcomm.F
  engine/source/output/sortie_main.F
Labels: enhancement

#3953 compatibility with -ffixed-line-length-132 gfortran flag
  starter/source/devtools/hm_reader/hm_get_float_array_2indexes.F
  starter/source/interfaces/interf1/lecins.F
  starter/source/materials/mat/mat092/law92_nlsqf.F90
Labels: refactoring

#4010 enhancement of unloading for Fail=0 when tcut is used
  engine/source/materials/mat/mat090/sigeps90.F
Labels: enhancement, important
