Repository OpenRadioss/OpenRadioss, pull requests merged in 2025-01, with the labels that each got.

#3269 Correct compatibility check of user materials for shells with Ismstr=10
  starter/source/elements/sh3n/coque3n/c3grtails.F
  starter/source/elements/shell/coque/cgrtails.F
Labels: bug, starter

#3250 Add check of variable consistency in /TABLE input
  starter/source/output/message/starter_message_description.txt
  starter/source/tools/curve/hm_read_table.F
  starter/source/tools/curve/hm_read_table2_1.F
Labels: enhancement, starter

#3254 /H3D and /ANIM : volumetric strain output
  engine/source/output/anim/generate/dfunc0.F
  engine/source/output/anim/generate/dfunc6.F
  engine/source/output/anim/generate/dfuncc.F
  engine/source/output/anim/generate/genani.F
  engine/source/output/anim/reader/anim_dcod_key_0.F
  engine/source/output/h3d/h3d_results/h3d_quad_scalar_1.F90
  engine/source/output/h3d/h3d_results/h3d_solid_scalar_1.F
  engine/source/output/h3d/h3d_results/h3d_sph_scalar.F
  engine/source/output/h3d/input_list/h3d_list_quad_scalar.F
  engine/source/output/h3d/input_list/h3d_list_solid_scalar.F
  engine/source/output/h3d/input_list/h3d_list_sph_scalar.F
Labels: enhancement

#3255 /EOS/GRUNEISEN : new P0 and PSH parameters
  common_source/eos/eosmain.F
  common_source/eos/gruneisen.F
  hm_cfg_files/config/CFG/radioss2025/MAT/mat_EOS.cfg
  starter/source/materials/eos/hm_read_eos_gruneisen.F
Labels: enhancement

#3221 /EBCS/PROPERGOL: inlet with combustion model
  common_source/modules/array_mod.F
  common_source/modules/boundary_conditions/ebcs_mod.F90
  common_source/modules/mat_elem/eos_param_mod.F90
  common_source/output/restart/write_bcs_wall.F90
  engine/CMake_Compilers/legacy_fortran.cmake
  engine/source/ale/alemain.F
  engine/source/assembly/vitesse.F
  engine/source/boundary_conditions/ebcs/ebcs11.F90
  engine/source/boundary_conditions/ebcs/ebcs_main.F
  engine/source/engine/resol.F
  engine/source/engine/resol_init.F
  engine/source/mpi/nodes/spmd_sd_xv_inter1.F90
  engine/source/multifluid/multi_ebcs.F
  engine/source/multifluid/multi_propergol_ebcs.F90
  engine/source/multifluid/multi_timeevolution.F
  engine/source/output/restart/rdresb.F
  engine/source/output/restart/read_eosparam.F90
  engine/source/output/restart/write_eosparam.F90
  engine/source/output/restart/wrrestp.F
  hm_cfg_files/config/CFG/radioss2025/LOADS/ebcs_propergol.cfg
  hm_cfg_files/config/CFG/radioss2025/data_hierarchy.cfg
  starter/source/boundary_conditions/ebcs/findele.F
  starter/source/boundary_conditions/ebcs/hm_read_ebcs_fluxout.F
  starter/source/boundary_conditions/ebcs/hm_read_ebcs_gradp0.F
  starter/source/boundary_conditions/ebcs/hm_read_ebcs_inip.F
  starter/source/boundary_conditions/ebcs/hm_read_ebcs_iniv.F
  starter/source/boundary_conditions/ebcs/hm_read_ebcs_monvol.F
  starter/source/boundary_conditions/ebcs/hm_read_ebcs_normv.F
  starter/source/boundary_conditions/ebcs/hm_read_ebcs_nrf.F
  starter/source/boundary_conditions/ebcs/hm_read_ebcs_pres.F
  starter/source/boundary_conditions/ebcs/hm_read_ebcs_propergol.F90
  starter/source/boundary_conditions/ebcs/hm_read_ebcs_valvin.F
  starter/source/boundary_conditions/ebcs/hm_read_ebcs_valvout.F
  starter/source/boundary_conditions/ebcs/hm_read_ebcs_vel.F
  starter/source/boundary_conditions/ebcs/iniebcs.F
  starter/source/boundary_conditions/ebcs/iniebcs_dp.F
  starter/source/boundary_conditions/ebcs/iniebcs_propergol.F90
  starter/source/boundary_conditions/ebcs/read_ebcs.F
  starter/source/boundary_conditions/ebcs/split_ebcs.F
  starter/source/elements/reader/hm_read_solid.F
  starter/source/elements/solid_2d/quad/lce16q.F
  starter/source/elements/solid_2d/quad/reordr.F
  starter/source/interfaces/intbuf/intbuf_ini_starter.F
  starter/source/interfaces/inter2d1/i1tid2.F
  starter/source/interfaces/inter2d1/inint2.F
  starter/source/materials/eos/hm_read_eos.F
  starter/source/materials/eos/hm_read_eos_ideal_gas.F
  starter/source/materials/mat/write_eosparam.F90
  starter/source/output/message/starter_message_description.txt
  starter/source/restart/ddsplit/ddsplit.F
  starter/source/spmd/domdec2.F
  starter/source/starter/lectur.F
  starter/source/tools/curve/hm_read_table2_1.F
Labels: enhancement

#3297 Correct scale factor on input radius in /PLCYL
  engine/source/loads/general/load_pcyl/press_seg3.F
Labels: bug, engine

#3305 Correction of table index value after previous development
  starter/source/materials/tools/func_table_copy.F90
Labels: bug

#3310 /MAT/LAW21 : fixing unloading behavior
  engine/source/materials/mat/mat021/m21law.F
  engine/source/materials/mat_share/mmain.F90
Labels: bug

#3311 /MAT/LAW51 : input compatibility with /MAT/PLAS_JOHNS (LAW2)
  starter/source/materials/mat/mat051/fill_buffer_51.F
Labels: enhancement

#3352 Missing arg wfext
  engine/source/ale/alemain.F
  engine/source/engine/resol.F
Labels: bug

#3358 missing arguments
  engine/source/ale/grid/alewdx.F
  engine/source/engine/resol.F
  engine/source/multifluid/multi_ebcs.F
  engine/source/multifluid/multi_propergol_ebcs.F90
Labels: bug

#3364 revert storage of material density and bulk in mulaw.F90
  engine/source/materials/mat_share/mulaw.F90
Labels: bug

#3365 Fix missing definition of Poisson's ratio
  engine/source/materials/mat/mat057/sigeps57c.F90
Labels: important
