Repository OpenRadioss/OpenRadioss, pull requests merged in 2025-04, with the labels that each got.

#3590 add missed implicit part in 967f3a52d7d500ede31fc130eb62a6bbc9e7235e
  engine/source/elements/elbuf/alloc_elbuf_imp.F
  engine/source/elements/elbuf/copy_elbuf_1.F
  engine/source/materials/mat_share/cmain3.F
Labels: important

#3586 correction to remove hourglass force after rupture
  engine/source/elements/solid/solide/s_hg5.F
  engine/source/elements/solid/solidez/shour_ctl.F90
Labels: important

#3588 add bucket sort in case of huge surf/surf input in interface type2 to avoid performance issues
  starter/source/interfaces/inter3d1/select_s2s.F90
Labels: important

#3595 Correction of MDS initialization in Radioss engine
  engine/source/engine/radioss2.F
  engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F
  starter/source/user_interface/uaccess.F
Labels: bug, important

#3599 Add condition for array allocation in MODE output
  engine/source/output/h3d/h3d_build_fortran/lech3d.F
Labels: important

#3602 /LOAD/PBLAST : improving warning messages
  engine/source/loads/pblast/pblast_1.F
  engine/source/loads/pblast/pblast_2.F
  engine/source/loads/pblast/pblast_3.F
  starter/source/loads/pblast/hm_read_pblast.F
Labels: important

#3604 Correction of input function update in /mat/law70
  starter/source/materials/mat/hm_read_mat.F90
  starter/source/materials/mat/mat070/law70_table.F
  starter/source/materials/read_material_models.F
  starter/source/materials/tools/table_values_2d.F
  starter/source/starter/lectur.F
Labels: bug, important

#3605 correction of wrong Starter output message of interface type2 surf/surf
  starter/source/interfaces/inter3d1/i2_surfi.F90
  starter/source/interfaces/interf1/lecins.F
  starter/source/output/message/starter_message_description.txt
  starter/source/starter/lectur.F
Labels: important

#3622 fix of regression due to merge
  starter/source/elements/elbuf_init/elbuf_ini.F
Labels: important

#3625 fix bug when E0 is set to zero
  starter/source/materials/mat/mat070/law70_upd.F
Labels: bug, important

#3624 /TABLE : slope calculation fixed
  starter/source/materials/mat/mat163/law163_upd.F90
  starter/source/materials/tools/table_slope.F
Labels: important

#3645 Correct MDS variable allocation at the beginning of Radioss engine
  engine/source/engine/radioss2.F
Labels: bug, engine, important

#3648 DAMP freq range - restart file issue
  starter/source/general_controls/damping/hm_read_damp.F
  starter/source/starter/lectur.F
Labels: important

#3650 fix from previous commit
  common_source/eos/eosmain.F
  engine/source/ale/grid/alewdx.F
  engine/source/materials/mat_share/mmain.F90
  qa-tests/miniqa/OPTIONS/desacti/test2/version_5/data/ref.extract
  qa-tests/miniqa/OPTIONS/desacti/test2/version_5/reference/HYPEA006.gz
  qa-tests/miniqa/OPTIONS/desacti/test2/version_5/reference/HYPET01
  qa-tests/miniqa/OPTIONS/desacti/test2/version_5/reference/HYPE_0000.out
  qa-tests/miniqa/OPTIONS/desacti/test2/version_5/reference/HYPE_0001.out
  qa-tests/miniqa/SUBMODEL/update_v_100/ACTIV/data/ref.extract
  qa-tests/miniqa/SUBMODEL/update_v_100/ACTIV/reference/HYPE_SUBA005.gz
  qa-tests/miniqa/SUBMODEL/update_v_100/ACTIV/reference/HYPE_SUBT01
  qa-tests/miniqa/SUBMODEL/update_v_100/ACTIV/reference/HYPE_SUB_0000.out
  qa-tests/miniqa/SUBMODEL/update_v_100/ACTIV/reference/HYPE_SUB_0001.out
Labels: bug

#3665 /LOAD/PBLAST : new Ishape flag for Surface Burst Model
  engine/source/loads/pblast/pblast_2.F
  hm_cfg_files/config/CFG/radioss2026/LOADS/pblast.cfg
  starter/source/loads/pblast/hm_read_pblast.F
Labels: enhancement

#3676 /LOAD/PBLAST:cosinus update for Ishape=1,2
  engine/source/loads/pblast/pblast_2.F
  starter/source/loads/pblast/hm_read_pblast.F
Labels: bug
