Repository OpenRadioss/OpenRadioss, pull requests merged in 2025-02, with the labels that each got.

#3344 /MAT/LAW151 : Ideal gas temperature
  common_source/eos/idealgas.F
Labels: enhancement

#3355 /TH/BRIC : new available output (VSTRAIN and WPLA)
  engine/source/output/th/hist2.F
  engine/source/output/th/thquad.F
  engine/source/output/th/thsol.F
  starter/source/output/th/hm_read_thgrou.F
  starter/source/output/th/th_titles.F90
  starter/source/output/th/write_thnms1.F90
Labels: enhancement

#3390 /CONVEC : noninitialized variable was initialized in wrong place
  engine/source/constraints/thermic/convec.F
Labels: bug, engine

#3359 include files 'atomic.inc' and 'atomend.inc' removed
  common_source/eos/eospolyno.F
  common_source/eos/idealgas.F
  common_source/eos/idealgas_vt.F
  common_source/eos/lszk.F
  common_source/eos/murnaghan.F
  common_source/eos/nasg.F
  common_source/eos/noble_abel.F
  common_source/eos/osborne.F
  common_source/eos/powder_burn.F
  common_source/eos/stiffgas.F
  common_source/eos/tabulated.F
  engine/share/spe_inc/atomend.inc
  engine/share/spe_inc/atomic.inc
  engine/source/airbag/mhvis3.F
  engine/source/ams/sms_gravit.F
  engine/source/constraints/general/rwall/rgwalc.F
  engine/source/constraints/general/rwall/rgwall.F
  engine/source/constraints/general/rwall/rgwalp.F
  engine/source/constraints/general/rwall/rgwals.F
  engine/source/elements/joint/rbilan33.F
  engine/source/elements/shell/coque/chsti3.F
  engine/source/elements/shell/coque/chvis3.F
  engine/source/elements/solid/solide/fhvis3.F
  engine/source/elements/solid/solide/s_hg5.F
  engine/source/elements/solid/solide/shvis3.F
  engine/source/elements/solid_2d/quad/qhvis2.F
  engine/source/elements/sph/splissv.F
  engine/source/elements/sph/sponfprs.F
  engine/source/elements/sph/sponfv.F
  engine/source/elements/sph/sponof1.F
  engine/source/elements/sph/sponof2.F
  engine/source/elements/spring/r23bilan.F
  engine/source/elements/spring/r3bilan.F
  engine/source/elements/spring/r5bilan.F
  engine/source/elements/spring/rbilan.F
  engine/source/interfaces/int14/i14frt.F
  engine/source/interfaces/int15/i15ass.F
  engine/source/interfaces/inter3d/i3fri3.F
  engine/source/loads/general/forcefingeo.F
  engine/source/loads/general/forcepinch.F
  engine/source/loads/general/grav/gravit.F
  engine/source/loads/general/grav/gravit_fvm_fem.F
  engine/source/loads/general/load_centri/cfield.F
  engine/source/loads/general/load_pressure/load_pressure.F
  engine/source/loads/general/pfluid/pfluid.F
  engine/source/materials/mat/mat041/sigeps41.F
  engine/source/materials/mat_share/meint.F
  engine/source/mpi/interfaces/spmd_int.F
  engine/source/mpi/interfaces/spmd_tri25vox0.F
  engine/source/multifluid/multi_evolve_global.F
  starter/share/spe_inc/atomend.inc
  starter/share/spe_inc/atomic.inc
Labels: refactoring

#3466 Correction of scale factor reading for /MAT/LAW50 in starter
  starter/source/materials/mat/mat050/hm_read_mat50.F90
Labels: bug, starter
